abbr --add gb 'git branch'
abbr --add gr 'git remote'
abbr --add go 'git switch'
abbr --add gs 'git status'
abbr --add gd 'git diff'
abbr --add ga 'git add'
abbr --add gc 'git commit -m'
abbr --add gt 'git tag -s'
abbr --add gm 'git merge'
abbr --add gp 'git push'
# abbr --add gpl 'git pull'
abbr --add gplum 'git pull upstream master'
abbr --add gplom 'git pull origin master'
abbr --add grpo 'git remote prune origin --dry-run'
abbr --add gl 'git log'
abbr --add gla 'git log --all --graph --oneline --decorate -12'
abbr --add gld 'git log --graph --pretty=format:"%C(auto)%h%Creset %C(cyan)%cs%Creset %s"'
